packages/modules/teams/lib/components/TeamForm.vue, packages/modules/teams/lib/store/teams.js
https://app.asana.com/0/1199229333810002/1200528648459949/f
=> chore(@deip/teams-module): add success and error events to TeamForm

packages/modules/users/lib/components/Avatar/UserAvatar.vue, packages/modules/users/lib/users-module.js, packages/utilities/platform-fns/lib/mixins/userHelpers.js
https://app.asana.com/0/1199229333810002/1200528648459967/f
=> Add $currentUser.exists

packages/modules/auth/lib/store/index.js
https://app.asana.com/0/1199229333810002/1200484912500314
=> fix(@deip/auth-module): fix sign in by email

packages/utilities/schema-renderer/lib/components/schema-renderer/schema-renderer.js
https://app.asana.com/0/1199229333810002/1200557400888137
=> fix(@deip/schema-renderer): fix cleaning form field value

packages/modules/teams/lib/components/TeamForm.vue, packages/utilities/platform-fns/lib/helpers/attributes.js
https://app.asana.com/0/1199229333810002/1200562067430414
=> Team create fix

packages/modules/fundraising/lib/store/index.js
https://app.asana.com/0/1199229333810002/1200562067430424/f
=> chore(@deip/fundraising-module): save data to store in getContributionsHistory action

packages/modules/auth/lib/components/AuthPasswordRestore.vue, packages/modules/auth/lib/components/AuthSignUp.vue, packages/modules/auth/lib/locales/en.js, packages/modules/auth/lib/store/index.js
Waiting for fixes in the backend
=> WIP: chore(@deip/auth-module): remove username from Sign up and Restore password forms

packages/modules/fundraising/lib/components/Widget/FundraisingWidget.vue
Fixed auto-update of **Fundraising widget**
Now the widget updates data depending on the type of state in which it is,
for the time that can be set by the "autoUpdateTime" props (by default 1 minute)
=> fix: fixed data auto update on the fundraising widget

packages/common/vue-layout-schema/lib/builder/components/builder/vls-builder.scss, packages/modules/layouts/lib/components/builder/layout-builder.vue
fix(@deip/vue-layout-schema): builder styles
=> refact(@deip/layouts-module): replace with vls-builder

packages/plugins/VuetifyExtended/lib/components/VexInput/VexDateInput/VexDateInput.vue
- Fixed behavior of the calendar by clicking on the icon 
- Added wrapper functions to handle other events
=> fix(@deip/vuetify-extended): calendar icon doesn't work

.eslintrc, packages/common/eslint-config/index.js, packages/common/toolbox/lib/classSingleton.js, packages/common/toolbox/lib/decorators/singletonDecorator.js, packages/services/Http/index.js, packages/services/Http/lib/HttpError.js, packages/services/Http/lib/HttpService.js, packages/services/Http/lib/HttpServiceV2.js, packages/services/Http/package.json, packages/services/Search/lib/SearchHttp.js, packages/services/Team/lib/TeamHttp.js, packages/services/Team/lib/TeamService.js, packages/services/Team/package.json
- added HttpError type and handler
- added HttpService v2 with ability to handle HttpError and canceled requests
- TeamService refactored for work with HttpService v2 and error handler
- added decorator for create class singleton
- added helper for create singleton getter
=> refactor(@deip/teams-module, @http-module): added http error

packages/modules/auth/lib/components/AuthSignUp.vue, packages/modules/auth/lib/locales/en.js
- added new **vex-password-repeat-input** component to **AuthSignUp** Form
- added new translation
=> feat(@deip/auth-module):add double password field to Sign up Form

packages/plugins/Validation/lib/ValidationPlugin.js, packages/plugins/Validation/lib/locales/en.js, packages/plugins/Validation/lib/rules.js
- Change Vee-validate email rule to custom rule
- Added verification of the email address by the number of entered characters
- Added new locale translation - email
=> feat(@deip/validation-plugin):Add email validation rule

packages/common/toolbox/__tests__/classSingleton.test.js
added tests for: 
- classSingleton method
- createInstanceGetter method
=> test(@deip/toolbox): added tests

packages/modules/users/lib/components/Avatar/UserAvatar.vue, packages/modules/users/lib/mixins/userHelpers.js
- Now the user's avatar is updated when the user profile is updated
- Fixed image caching problem
=> fix(@deip/users-module):fix avatar image update

packages/common/vue-layout-schema/lib/builder/components/builder/vls-builder.scss, packages/common/vue-layout-schema/lib/builder/components/canvas/vls-builder-canvas.js, packages/common/vue-layout-schema/lib/builder/components/canvas/vls-builder-canvas.scss, packages/common/vue-layout-schema/lib/builder/components/settings/vls-builder-settings.js, packages/common/vue-layout-schema/lib/builder/mixins/builder-mixin.js, packages/common/vue-layout-schema/lib/builder/store/index.js, packages/common/vue-layout-schema/package.json
- https://app.asana.com/0/1199229333810002/1201414599015392
- add raw display for debugging
- add jsDoc
- refact canvas methods
- add «undefined» block type for canvas
- remove  deep find from getContainerNodeInfo
- add store getter for flat block list
=> fix(@deip/vue-layout-schema): refact and fixes

packages/modules/auth/lib/store/auth.js
changed error description if user not found
=> fix(@deip/auth-module):fix err text [ if user not found ]

packages/casimir/modules/attributes/lib/components/attribute-edit.js, packages/casimir/modules/attributes/lib/components/attribute-read.js, packages/casimir/modules/attributes/lib/components/attribute-set.js, packages/casimir/modules/attributes/lib/mixins/attribute.js, packages/casimir/modules/attributes/package.json, packages/casimir/modules/teams/lib/components/TeamForm.vue, packages/casimir/modules/teams/package.json
часть кода под випом. прошу тупо не обращать внимания ибо там обнаружена отдельная боль этого дела :(
=> feat(@deip/attributes-module): add custom attribute type

packages/casimir/modules/users/lib/components/Form/UserForm.vue
https://app.asana.com/0/1200949344985432/1201379845077106
=> fix(@deip/users-module): change renderer

packages/casimir/modules/attributes/lib/components/AttributeUrl/AttributeUrlSet.js
Change label name from **Label** to **Link**
=> fix(@deip/attributes-module):change label name

packages/casimir/modules/layouts/lib/store/layoutsStore.js, packages/casimir/services/Layout/lib/LayoutService.js
fix create/update/delete in case of new re…
=> fix(@deip/layout-service)

packages/casimir/modules/contract-agreements/lib/locales/en.js
* fixed i18n translation contractAgreements component
=> fix i18n translation

packages/casimir/modules/assets/lib/store/assets.js, packages/casimir/modules/attributes/lib/store/attributesStore.js, packages/casimir/modules/bookmarks/lib/store/index.js, packages/casimir/modules/contract-agreements/lib/store/index.js, packages/casimir/modules/document-templates/lib/store/index.js, packages/casimir/modules/domains/lib/store/index.js, packages/casimir/modules/wallet/lib/store/index.js, packages/casimir/services/Assets/lib/AssetsHttp.js, packages/casimir/services/Assets/lib/AssetsService.js, packages/casimir/services/Attributes/lib/AttributesHttp.js, packages/casimir/services/Attributes/lib/AttributesService.js, packages/casimir/services/Bookmark/lib/BookmarkHttp.js, packages/casimir/services/Bookmark/lib/BookmarkService.js, packages/casimir/services/ContractAgreement/lib/ContractAgreementHttp.js, packages/casimir/services/ContractAgreement/lib/ContractAgreementService.js, packages/casimir/services/DocumentTemplate/lib/DocumentTemplateHttp.js, packages/casimir/services/DocumentTemplate/lib/DocumentTemplateService.js, packages/casimir/services/Domains/lib/DomainsHttp.js, packages/casimir/services/Domains/lib/DomainsService.js
=> refactor: rename methods in services

packages/casimir/modules/auth/lib/store/auth.js, packages/casimir/modules/auth/lib/store/currentUser.js, packages/casimir/modules/contract-agreements/lib/store/index.js, packages/casimir/modules/investment-opportunities/lib/store/index.js, packages/casimir/modules/notifications/lib/store/index.js, packages/casimir/modules/project-content/lib/store/projectContent.js, packages/casimir/modules/project-content/lib/store/projectContentDrafts.js, packages/casimir/modules/projects/lib/store/index.js, packages/casimir/modules/teams/lib/store/teams.js, packages/casimir/modules/users/lib/store/index.js, packages/casimir/services/InvestmentOpportunity/lib/InvestmentOpportunityHttp.js, packages/casimir/services/InvestmentOpportunity/lib/InvestmentOpportunityService.js, packages/casimir/services/Notification/lib/NotificationHttp.js, packages/casimir/services/Notification/lib/NotificationService.js, packages/casimir/services/Project/lib/ProjectHttp.js, packages/casimir/services/Project/lib/ProjectService.js, packages/casimir/services/ProjectContent/lib/ProjectContentHttp.js, packages/casimir/services/ProjectContent/lib/ProjectContentService.js, packages/casimir/services/Proposals/lib/ProposalsHttp.js, packages/casimir/services/Proposals/lib/ProposalsService.js, packages/casimir/services/Review/lib/ReviewHttp.js, packages/casimir/services/Review/lib/ReviewService.js, packages/casimir/services/Team/lib/TeamHttp.js, packages/casimir/services/Team/lib/TeamService.js, packages/casimir/services/User/lib/UserHttp.js, packages/casimir/services/User/lib/UserService.js
=> refactor: rename methods im services

packages/casimir/modules/users/lib/store/index.js
* Added profile status constant
* Unused function changed
=> fix(@deip/users-module):fix store functional

packages/casimir/plugins/VuetifyExtended/lib/components/VexImageInput/VexImageInput.vue
* fixed bug with file format when opening downloaded image
* now you can save the image in the same format in which it was loaded
=> fix(@deip/vuetify-extended):fix vex-image-input

packages/casimir/modules/assets/index.js, packages/casimir/modules/assets/lib/components/CreateTokenForm/CreateFungibleTokenForm.vue, packages/casimir/modules/assets/lib/locales/en.js, packages/casimir/modules/assets/lib/store/balances.js, packages/casimir/modules/investment-opportunities/lib/components/crowdfunding/Create/CreateCrowdfundingForm.vue, packages/casimir/modules/investment-opportunities/lib/locales/en.js
* renamed ntf to ft in locales
* renamed `CreateNonFundableForm` and its exports name
* connect `FungibleTokenService` to assets store
=> rename ntf to ft 

packages/casimir/services/Attributes/__test__/unit/AttributesHttp.test.js, packages/casimir/services/Attributes/__test__/unit/AttributesService.test.js
for AttributesHttp.test.js and AttributesService.js
=> test(@deip/Attributes-service): added tests 

packages/casimir/modules/nft-collections/lib/components/NftCollectionDetails/NftCollectionDetails.vue, packages/casimir/modules/nft-collections/lib/components/NftCollectionForm/NftCollectionForm.vue, packages/casimir/modules/nft-items/lib/components/common/NftItemsInfiniteScroll/NftItemsInfiniteScroll.vue, packages/casimir/modules/nft-items/lib/components/content/List/NftItemsList.vue, packages/casimir/modules/nft-items/lib/components/drafts/Details/NftItemDraftDetails.vue, packages/casimir/modules/nft-items/lib/components/drafts/List/NftItemDraftsList.vue, packages/casimir/services/token/src/services/non-fungible/NonFungibleTokenService.js
feat(@casimir/nft-collections-module,@casimir/nft-items-module,@casimir/token-service): CAS-100 metadata moved into data section
https://deip.atlassian.net/browse/CAS-100
=> feat(@casimir/nft-collections-module) CAS-100 metadata moved into data section 
